server:
  port: 9000

dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user
  registry:
    address: zookeeper://192.168.92.131:2181?backup=192.168.92.131:2182,192.168.92.131:2183
